# Make virtualenvwrapper work
if [[ -e /usr/local/bin/virtualenvwrapper.sh ]]; then
  export WORKON_HOME=~/venvs
  mkdir -p $WORKON_HOME
  source /usr/local/bin/virtualenvwrapper.sh
fi

# IP addresses
alias wanip="dig +short myip.opendns.com @resolver1.opendns.com"
alias whois="whois -h whois-servers.net"

# File size
alias fs="stat -f '%z bytes'"
alias df="df -h"

# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Color for grep.
export GREP_OPTIONS='--color=auto'

# SSH auto-completion based on entries in known_hosts.
if [[ -e ~/.ssh/known_hosts ]]; then
  complete -o default -W "$(cat ~/.ssh/known_hosts | sed 's/[, ].*//' | sort | uniq | grep -v '[0-9]')" ssh scp stfp
fi

# Git auto-completion
if [[ -e ~/.git-completion.bash ]]; then
  source ~/.git-completion.bash
fi


# ==================================================
# Deal with platform-specific stuff.

# From: http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
SOURCE="${BASH_SOURCE[0]}"
DIR="$( dirname "$SOURCE" )"
while [ -h "$SOURCE" ]
do
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done
DOTFILES_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

SUBFILE=$DOTFILES_DIR/`uname`/bashrc
if [[ -e "$SUBFILE" ]]
then
  echo "Loading OS-specific settings..."
  source $SUBFILE
fi

# Deal with computer-specific stuff.
if [[ -e ~/.bash_specific ]]
then
  echo "Loading computer-specific settings..."
  source ~/.bash_specific
fi

# Unset all unneeded variables.
unset SOURCE
unset DIR
unset SUBFILE
