" Disable compatibility with vi
set nocompatible

" Who uses a text editor without syntax highlighting these days?
syntax on

" Disable the distracting intro screen.
set shm=atI

" Don't redraw the screen during macros.
set lazyredraw

" Don't syntax highlight super-long lines (for performance)
set synmaxcol=2048

" Improves redrawing for "newer" computers (where "newer" is defined as "not 
" ancient").
set ttyfast

" Disable backup (useful since most files are version-controlled)
set nobk nowb noswf

" Show line numbers, width = 5
set number
set numberwidth=5

" Display the current mode in the status bar
set showmode

" Show file in titlebar
set title

" When the page starts to scroll, keep the cursor 3 lines from top/bottom
set scrolloff=3      

" Allow the cursor to go to 'invalid' locations. Note: disabled becuase it's irritating.
" set virtualedit=all

" Display current column/line in bottom right
set ruf=%l:%c ruler 

" Show incomplete command at bottom right, please.
set showcmd

" Allow backspacing over anything
set bs=2

" Only be case sensitive when search contains uppercase letters.
set ignorecase smartcase

" Always display a status line
set laststatus=2 

" Enable command-line tab completion (REALLY useful).
set wim=full wildmenu

" Hide irrelevent matches when completing stuff.
set wildignore+=*.o,*.obj,*.pyc,*.DS_Store,*.db,.git,*.bak,.svn,*.swp

" Allow hidden buffers (REALLY useful as well).
set hidden

" Enable mouse support.
set mouse=a

" Enable unicode support (seriously).
set enc=utf-8

" Highlight search matches!
set hlsearch

" Search incrementally
set incsearch
set wrapscan

" Show tabs as ">"
set list
set listchars=tab:>.

" Show matching brackets
set showmatch 

" Tabs are spaces, width 4, and are treated as single chars.
set expandtab
set tabstop=4
set softtabstop=4

" Color scheme
colorscheme desert

" Turn off tab-replacement for Makefiles
autocmd FileType make setlocal noexpandtab

" Add json syntax highlighting
au BufNewFile,BufRead *.json set ft=javascript

" Command to sudo save file
cmap w!! w !sudo tee % >/dev/null

" If it exists, include user's local vim config
if filereadable(expand("~/.vimrc.local"))
    source ~/.vimrc.local
endif

